Post http://localhost:7071/api/purchase
Content-Type: application/json

{
     "ProductId" : 2222, 
     "Quantity" : 10, 
     "CustomerName" : "Shobika", 
     "CustomerEmail" : "shobi@gmail.com", 
     "PurchasePrice" : 50.50
}