Post http://localhost:7071/api/purchase
Content-Type: application/json

{
     "ProductId" : 555, 
     "Quantity" : 307, 
     "CustomerName" : "NNNn", 
     "CustomerEmail" : "NNM@gmail.com", 
     "PurchasePrice" : 135.50
}
####

Get
http://localhost:7071/api/purchase/da21b93f-0019-4be2-93ff-fea70a48bada