Post http://localhost:7071/api/purchase
Content-Type: application/json

{
     "ProductId" : 1500, 
     "Quantity" : 600, 
     "CustomerName" : "mommypig", 
     "CustomerEmail" : "mommy@gmail.com", 
     "PurchasePrice" : 1000.0
}
####

Get
http://localhost:7071/api/purchase/da21b93f-0019-4be2-93ff-fea70a48bada